Step2 Proxy와 Bean 의존관계
next-step/jwp-aop pull request #82
Opened 2022-09-24 04:22 UTC by DoLiLu

안녕하세요

Step 2 Proxy와 Bean 의존관계 미션 리뷰 요청합니다.

감사합니다.

2022-09-25 07:05 UTC, sah3122 requested changes
2단계 미션 구현 잘해주셨네요 👍 
다음 미션을 진행하기전 사소한 생각거리를 남겨두었는데 확인 부탁드려요 🙏

2022-09-25 07:05 UTC, sah3122 commented on src/main/java/core/aop/ProxyFactoryBean.java
> +        if (availableJDKDynamicProxy()) {
jdk proxy 를 사용할수 있는 경우에 JDK Proxy로 빈을 생성하도록 구현해주셨네요 👍 
Spring 기준으로 기본 proxy 생성 방식은 cglib을 사용하도록 되어 있는것을 알고 계실거에요. 

추후엔 프레임워크 사용자 기준으로 cglib proxy 를 사용할수 있도록 우선순위를 조정할수있도록 해주는것도 좋을것 같아요 !

2022-09-25 07:05 UTC, sah3122 commented on src/main/java/core/aop/Advisor.java
> +public interface Advisor {
Advisor 인터페이스 정의 👍

2022-09-25 07:05 UTC, sah3122 commented on src/main/java/core/aop/PointcutAdvisor.java
> +public class PointcutAdvisor implements Advisor {
Pointcut, advice를 활용하여 구현 잘해주셨네요 👍

2022-09-25 07:05 UTC, sah3122 commented on src/main/java/core/aop/Advisor.java
> +    Object invoke(Object object, Method method, Object[] args);
advice 의 invoke, pointcut의 matches 메소드를 호출하는 abstract class 를 구현해두는건 어떻게 생각하세요 ?

2022-09-25 07:05 UTC, sah3122 commented on src/main/java/core/aop/CGLibAopProxy.java
> +        };
method 결과값이 string 이 아닌경우는 어떻게 처리할수 있을까요 ?

2022-09-25 07:05 UTC, sah3122 commented on src/test/java/core/aop/PointcutAdvisorTest.java
> +class PointcutAdvisorTest {
꼼꼼한 테스트 코드 👍

2022-09-25 07:19 UTC, DoLiLu commented on src/main/java/core/aop/Advisor.java
> +    Object invoke(Object object, Method method, Object[] args);
구현해보겠습니다.

2022-09-25 07:19 UTC, DoLiLu commented on src/main/java/core/aop/ProxyFactoryBean.java
> +        if (availableJDKDynamicProxy()) {
변경 하였습니다.

2022-09-25 07:37 UTC, DoLiLu commented on src/main/java/core/aop/CGLibAopProxy.java
> +        };
수정하였습니다.

2022-09-26 08:40 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
구현하신 코드를 보며 저도 많이 배우고 있어요 🙏 
다음 미션도 기대할게요 !

2022-09-26 08:40 UTC, sah3122 commented on src/main/java/core/aop/AbstractAopAdvisor.java
> +public abstract class AbstractAopAdvisor implements Advisor {
피드백 반영 👍

2022-09-26 08:41 UTC, merged